spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

  application:
    name: demo

  datasource:
#    개발
#    url: ${dev_mysql}
#    운영
    url: ${mysql}
    username: root
    password: whathelook
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  jwt:
    secret: ${secretKey}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${id}
            client-secret: ${secret}
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            개발
#            redirect-uri: http://localhost:5173/kakao/auth
#            운영
            redirect-uri: ${url}
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cloud:
  front:
#    개발
#    url: ${dev_url}
#    운영
    url: ${url}
  aws:
    s3:
      #개발
#      bucket: whathelook
#      운영
      bucket: whathelooks
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
#      개발
#      accessKey: ${dev_key}
#      운영
      accessKey: ${key}
#      개발
#      secretKey: ${dev_key}
#      운영
      secretKey: ${key}


springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

url:
  front: ${url}